"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { X } from "lucide-react";
import { useApp } from "@/lib/store";
import { useDialog } from "@/lib/ui/useDialog";

export const TOKEN_FACTORY_TERMS = "https://docs.tokenfactory.nebius.com/legal/terms-of-service";

/** The "Intended use and limitations" text from the project README, plus the dedication. */
export default function AboutDialog() {
  const open = useApp((s) => s.aboutOpen);
  const setOpen = useApp((s) => s.setAboutOpen);
  return <AnimatePresence>{open && <AboutInner key="about" onClose={() => setOpen(false)} />}</AnimatePresence>;
}

function AboutInner({ onClose }: { onClose: () => void }) {
  const reduced = !!useReducedMotion();
  const ref = useDialog<HTMLDivElement>(true, onClose);
  return (
    <motion.div
      className="fixed inset-0 z-50 flex items-center justify-center p-6"
      style={{ background: "rgb(10 14 20 / 0.6)" }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0, transition: { duration: 0.15 } }}
      transition={{ duration: 0.2 }}
      onMouseDown={(e) => e.target === e.currentTarget && onClose()}
    >
      <motion.div
        ref={ref}
        role="dialog"
        aria-modal="true"
        aria-labelledby="about-h"
        tabIndex={-1}
        className="panel flex max-h-full w-[640px] flex-col overflow-hidden"
        initial={reduced ? { opacity: 0 } : { opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.2, ease: [0.22, 1, 0.36, 1] }}
      >
        <div className="flex items-center justify-between border-b border-border px-6 py-3">
          <h2 id="about-h" className="text-xl font-medium">
            About WorldSeed
          </h2>
          <button className="btn-icon" aria-label="Close about" onClick={onClose}>
            <X size={16} aria-hidden />
          </button>
        </div>
        <div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-6 py-4 text-sm leading-6 text-text/90">
          <p className="text-base leading-6 text-text">
            A counterfactual planning simulator for the Key Bridge region of Baltimore. Change the road network, and every number is
            recomputed on it, in your browser.
          </p>
          <div className="card p-4">
            <p className="font-medium">Planning simulation, not dispatch.</p>
            <p className="text-muted">Simulated times on historical open data. Not affiliated with any agency or hospital. In an emergency, call 911.</p>
          </div>

          <h3 className="label pt-2">Intended use and limitations</h3>
          <p>
            <strong className="font-medium">Intended use.</strong> WorldSeed is a research and educational prototype for exploring counterfactual
            infrastructure-planning scenarios. It is not an emergency dispatch, triage, routing, or operational decision system, and it must not
            be used to direct, prioritize, or delay any real emergency response. In an emergency, call 911.
          </p>
          <p>
            <strong className="font-medium">Simulated results.</strong> All travel times, coverage figures, and other metrics are outputs of a
            simplified simulation using historical, possibly incomplete or outdated open data (OpenStreetMap, U.S. Census Bureau). They are not
            measurements or predictions of real-world performance and do not reflect the actual capabilities, staffing, capacity, or protocols of
            any hospital, fire, EMS, or government agency.
          </p>
          <p>
            <strong className="font-medium">AI-generated text.</strong> Intervention suggestions and explanations are generated by an AI language
            model and may be inaccurate. They are proposals for human review, not recommendations.
          </p>
          <p>
            <strong className="font-medium">No affiliation.</strong> Names of hospitals, stations, and agencies identify real-world locations only.
            WorldSeed is not affiliated with, endorsed by, or produced in cooperation with any of them, the State of Maryland, Baltimore City or
            County, the U.S. Census Bureau, the NTSB, or the OpenStreetMap Foundation.
          </p>
          <p>
            <strong className="font-medium">No warranty.</strong> Provided &quot;as is&quot; under the licenses below, without warranty of any kind.
          </p>

          <h3 className="label pt-2">Data and services</h3>
          <ul className="list-disc space-y-1 pl-5 text-muted">
            <li>
              Road network and places:{" "}
              <a className="underline decoration-border underline-offset-2 hover:text-text" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">
                &copy; OpenStreetMap contributors
              </a>
              , Open Database License (ODbL). The derived snapshot is licensed ODbL 1.0.
            </li>
            <li>Population, households and vehicles: U.S. Census Bureau, American Community Survey 5-year estimates. Boundaries: TIGER/Line. Jobs: LEHD LODES.</li>
            <li>
              Map tiles: OpenFreeMap, &copy; OpenMapTiles.
            </li>
            <li>
              AI: NVIDIA Nemotron via Nebius Token Factory (
              <a className="underline decoration-border underline-offset-2 hover:text-text" href={TOKEN_FACTORY_TERMS} target="_blank" rel="noreferrer">
                terms
              </a>
              ). Search: Tavily.
            </li>
          </ul>

          <p className="border-t border-border pt-4 text-muted">
            In memory of the six construction workers lost when the Francis Scott Key Bridge collapsed on March 26, 2024.
          </p>
        </div>
      </motion.div>
    </motion.div>
  );
}
